name: Gradle Build

on:
  push:
    branches: ["main", "renovate/*"]
  pull_request:

permissions:
  contents: write
  checks: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: temurin
        java-version: 21

    # A push will be from Renovate, so I can agree to the terms.
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      if: github.actor != 'andrewaylett' && github.event_name != 'push'
      with:
        dependency-graph: 'generate-and-submit'

    - name: Setup Gradle Build Scan
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      if: github.actor == 'andrewaylett' || github.event_name == 'push'
      with:
        dependency-graph: 'generate-and-submit'
        build-scan-publish: 'true'
        build-scan-terms-of-use-agree: 'yes'
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'

    - name: Upload JAR
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: JAR
        path: build/libs/*.jar

    - name: Upload Build Output
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: failure() # we don't care so much about working builds
      with:
        name: Built-Output
        path: |
          **/build/
          !**/cache/
          !**/caches/

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly
    - uses: andrewaylett/pre-commit-action@4c33be1c71b225ab32162e179494e63316ddf08c # v4
      with:
        extra_args: '--all-files --hook-stage pre-merge-commit'
