name: Gradle Build

on:
  push:
    branches: ["main", "renovate/*"]
  pull_request:

permissions:
  contents: read
  checks: write
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4

    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@cf701569b05ccdd861a76b8607a66d76f6fd4857 # v5
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'

    - name: Upload JAR
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: JAR
        path: build/libs/*.jar

    - name: Upload Build Output
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: failure() # we don't care so much about working builds
      with:
        name: Built-Output
        path: |
          **/build/
          !**/cache/
          !**/caches/

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0 # so we can work out our version correctly
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: '--all-files --hook-stage pre-merge-commit'
