name: Publish Plugin

on:
  release:
    types: [created]

permissions:
  contents: write
  checks: write
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0 # so we can work out our version correctly

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      with:
        dependency-graph: 'generate-and-submit'
        build-scan-publish: 'true'
        build-scan-terms-of-use-agree: 'yes'
        build-scan-terms-of-use-url: https://gradle.com/help/legal-terms-of-use

    - name: Publish to GitHub Packages
      run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to OSSRH
      run: ./gradlew --no-configuration-cache -Dorg.gradle.unsafe.isolated-projects=false publishMavenJavaPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
      env:
        OSSRH_TOKEN_USER: ${{ secrets.OSSRH_TOKEN_USER }}
        OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
